### PR TITLE
CHANGES

### PR DESCRIPTION
**Pull request by CDAGaming**
- Update Gradle Configuration (Update to 4.2, and Some cleanup)
- Code Cleanup
- Fixes Some Errors (Hopefully)

@SantaGitHub Can you check this a bit (Hopefully, I did it right this time 👍 )

### CODE REVIEW

**Comment by SantaGitHub** [comment]
Why update gradle?
Partially true. It will be necessary to correct the hands

**Comment by CDAGaming** [comment]
I updated Gradle just because (Possible Fixes and whatnot)
Added back The Imports i removed just in case MC requires them later

**Comment by CDAGaming** [comment]
i've also updated the remaining files that are erroring in #1 , 7 files in total

**Comment by CDAGaming** [comment]
PR adjusted to accomodate for fewizz 's Changes 👍

**Comment by fewizz** [comment]
New gradle version may break comp. with FG

**Comment by CDAGaming** [comment]
Hm, It might now that i think about it. Though, it didn't give any additional errors when i built with it (Besides our current 100 we have)
For compatibility however, ill revert it to 3.3 again in a bit

**Pull request closed without merging**
